name = "addictionx"
main = ".open-next/worker.js"
compatibility_date = "2026-08-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[vars]
NEXT_PUBLIC_SITE_URL = "https://addictionx.store"
EMAIL_FROM = "ADDICTIONX <hello@addictionx.store>"
AUTH_SECRET = "ohN5ZE9uqwRv3uS0KtMw7jVUDbG7hbqnOf/2y9tG+pU="
AUTH_TRUST_HOST = "true"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "327f164408f54c6e9641d066806e21d8"

[triggers]
crons = ["0 0 * * *"]
